---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package.
  npm:
    name: appium
    version: '1.6.6-beta'
    path: "{{ appium_install_location }}"

- name: Update uiautomator2 driver to latest version.
  npm:
    path: "{{ appium_install_location }}/node_modules/appium-uiautomator2-driver"
    state: latest
