---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package on version 1.6.1.
  npm:
    name: appium
    version: '1.6.6-beta'
    path: "{{ appium_install_location }}"
