---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package.
  command: npm install appium@{{ appium_version }} --prefix {{ appium_install_location }} --unsafe-perm true

- name: override appium-adb/build/lib/tools/system-calls.js file
  copy: src="roles/appium/templates/system-calls.js" dest={{ appium_install_location }}/node_modules/appium/node_modules/appium-adb/build/lib/tools/system-calls.js

