---
stf_private_host: 192.168.88.43
stf_public_host: stage.qaprosoft.com
stf_tcp_sub_port: 7250
stf_tcp_pub_port: 7270
selenium_hub_host: 192.168.88.43
selenium_hub_port: 4444

devices:
  - id: 5200dd5aec34b47b
    name: Samsung_Galaxy_A3
    adb_port: 5038
    min_port: 7401
    max_port: 7410
    proxy_port: 9000
