---
stf_private_host: <private_host>
stf_public_host: <public_host>
stf_tcp_sub_port: 7114
stf_tcp_pub_port: 7116
devices:
  - id: ZX1G22B3GG
    name: Motorola_Nexus_6
    adb_port: 5038
    min_port: 7401
    max_port: 7410
  - id: 410053d1c8c59555
    name: Samsung_Galaxy_Note_4
    adb_port: 5039
    min_port: 7411
    max_port: 7420
