---
stf_private_host: 192.168.88.107
stf_public_host: stage.qaprosoft.com
stf_tcp_sub_port: 7250
stf_tcp_pub_port: 7270
selenium_hub_host: 192.168.88.107
selenium_hub_port: 4444

devices:
  - id: PL2GAR9822804910
    name: Nokia_6_1
    adb_port: 5038
    min_port: 7401
    max_port: 7410
    proxy_port: 9000
